slam_toolbox:
  ros__parameters:
    use_sim_time: false
    publish_odom_tf: false
    use_scan_matching: true

    # TF-Frames
    base_frame: "base_link"
    odom_frame: "base_link"
    map_frame: "map"

    # SLAM-Modus
    mode: "lifelong"

    # Map-Handling
    publish_map: true
    publish_map_to_odom_transform: true
    map_update_interval: 0.5

    # Scan
    scan_topic: /scan
    max_laser_range: 16.0
    min_laser_range: 0.2
    resolution: 0.05
    minimum_time_interval: 0.5

    # Bewegungsfilter
    minimum_travel_heading: 0.3
    minimum_travel_distance: 0.2

    # Schleifenschluss
    do_loop_closing: true

    # Falls der Lidar zu schnell ist
    #throttle_scans: true

